server:
  port: 8080
  address: 127.0.0.1
eureka:
  client:
    #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
#定义服务名
spring:
  application:
    name: RegisterCenter